apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntestm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ntestm
  template:
    metadata:
      labels:
        app: ntestm
    spec:
      containers:
      - image: okteto.dev/ntestm:latest
        name: ntestm
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "bcb85b9c-b801-4804-96d8-c56bafc91914"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "2acb6fa2-8c6f-4895-b0ab-e7abad7684de"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/Share233"
